[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
#optimizer_runs越小部署时成本越小，用户调用成本越高
optimizer_runs = 10

remappings = ["@openzeppelin-contracts/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
